#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipmctl
Version  : 01.00.00.3262
Release  : 2
URL      : https://github.com/intel/ipmctl/archive/v01.00.00.3262.tar.gz
Source0  : https://github.com/intel/ipmctl/archive/v01.00.00.3262.tar.gz
Summary  : Manage Intel DC Optane persistent memory modules
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: ipmctl-bin
Requires: ipmctl-config
Requires: ipmctl-lib
Requires: ipmctl-license
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : doxygen
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : libsafec-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libndctl)
BuildRequires : pkgconfig(systemd)

%description
Oniguruma  ----   (C) K.Kosako <sndgk393 AT ybb DOT ne DOT jp>
http://www.geocities.jp/kosako3/oniguruma/

%package bin
Summary: bin components for the ipmctl package.
Group: Binaries
Requires: ipmctl-config
Requires: ipmctl-license

%description bin
bin components for the ipmctl package.


%package config
Summary: config components for the ipmctl package.
Group: Default

%description config
config components for the ipmctl package.


%package dev
Summary: dev components for the ipmctl package.
Group: Development
Requires: ipmctl-lib
Requires: ipmctl-bin
Provides: ipmctl-devel

%description dev
dev components for the ipmctl package.


%package doc
Summary: doc components for the ipmctl package.
Group: Documentation

%description doc
doc components for the ipmctl package.


%package lib
Summary: lib components for the ipmctl package.
Group: Libraries
Requires: ipmctl-license

%description lib
lib components for the ipmctl package.


%package license
Summary: license components for the ipmctl package.
Group: Default

%description license
license components for the ipmctl package.


%prep
%setup -q -n ipmctl-01.00.00.3262

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536547642
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1536547642
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ipmctl
cp BaseTools/License.txt %{buildroot}/usr/share/doc/ipmctl/BaseTools_License.txt
cp BaseTools/Source/C/BrotliCompress/LICENSE %{buildroot}/usr/share/doc/ipmctl/BaseTools_Source_C_BrotliCompress_LICENSE
cp LICENSE %{buildroot}/usr/share/doc/ipmctl/LICENSE
cp MdeModulePkg/Library/BrotliCustomDecompressLib/LICENSE %{buildroot}/usr/share/doc/ipmctl/MdeModulePkg_Library_BrotliCustomDecompressLib_LICENSE
cp MdeModulePkg/License.txt %{buildroot}/usr/share/doc/ipmctl/MdeModulePkg_License.txt
cp MdeModulePkg/Universal/RegularExpressionDxe/Oniguruma/COPYING %{buildroot}/usr/share/doc/ipmctl/MdeModulePkg_Universal_RegularExpressionDxe_Oniguruma_COPYING
cp MdePkg/License.txt %{buildroot}/usr/share/doc/ipmctl/MdePkg_License.txt
cp ShellPkg/License.txt %{buildroot}/usr/share/doc/ipmctl/ShellPkg_License.txt
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ipmctl
/usr/bin/ipmctl-monitor

%files config
%defattr(-,root,root,-)
%config /usr/etc/ipmctl.conf
/usr/lib/systemd/system/ipmctl-monitor.service

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libipmctl.so
/usr/lib64/pkgconfig/libipmctl.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/ipmctl/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libipmctl.so.2
/usr/lib64/libipmctl.so.2.0.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/ipmctl/BaseTools_Source_C_BrotliCompress_LICENSE
/usr/share/doc/ipmctl/LICENSE
/usr/share/doc/ipmctl/MdeModulePkg_Library_BrotliCustomDecompressLib_LICENSE
/usr/share/doc/ipmctl/MdeModulePkg_Universal_RegularExpressionDxe_Oniguruma_COPYING
